# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            What?
tagline:          "I'm sorry, but that didn't make any sense."
description:      'The incoherent ramblings of a Father, Software Engineer, Baseball Coach and all round オタク.'
url:              https://www.jeremycade.com
baseurl:          /

author:
  name:           'Jeremy Cade'
  url:            https://www.jeremycade.com

paginate:         1

# Additional Gems
gems:
    - jekyll-sitemap
    - jekyll-feed

# Collections
collections:
  snippets:
    output: true
