# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Que
tagline:          "I'm sorry, but that didn't make any sense."
description:      'The incoherent ramblings of a Father, Software Engineer, Academic in Training, Baseball Coach and all round nerd.'
url:              http://www.jeremycade.com
baseurl:          /

author:
  name:           'Jeremy Cade'
  url:            http://www.jeremycade.com

paginate:         5

# Additional Gems
gems:
    jekyll-sitemap
